// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed network-disconnect-svgrepo-com.svg
var resourceNetworkDisconnectSvgrepoComSvgData []byte
var ResourceNetworkDisconnectSvgrepoComSvg = &fyne.StaticResource{
	StaticName:    "assets/network-disconnect-svgrepo-com.svg",
	StaticContent: resourceNetworkDisconnectSvgrepoComSvgData,
}
